name: Git Action 실행시켜보기

on:
  push:
    branches:
      - main


jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 찍기
        run: echo "hello world"
      # 여러 문장을 작성하기
      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "하이루"
      # 참고: https://docs.github.com/en/actions/learn-github-actions/variables
      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
      - name: Github Actions Secret 변수 사용해보기
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_HOBBY }}